# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Set Gradle Version and Build Number"
  lane :set_full_version do 
		version = flutter_version()

		android_set_version_name(version_name: version['version_name'])

		android_set_version_code(version_code: version['version_code'])
	end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    set_full_version

    gradle(task: "clean bundle")

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "alpha"
    )
  end
end
